### ISSUE TITLE
ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by n-b37** [yn-sun/cnn-ga#11]
2020-08-25 10:54:39,366 INFO    : *************************
2020-08-25 10:54:39,367 INFO    : Initialize...
2020-08-25 10:54:39,375 INFO    : EVOLVE[0-gen]-Begin to evaluate the fitness
2020-08-25 10:54:39,375 INFO    : Begin to generate python files
2020-08-25 10:54:39,411 INFO    : Finish the generation of python files
2020-08-25 10:54:39,412 INFO    : Query fitness from cache
2020-08-25 10:54:39,413 INFO    : Total hit 0 individuals for fitness
2020-08-25 10:55:39,475 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-25 10:55:39,476 INFO    : Begin to train indi0000
Files already downloaded and verified
Files already downloaded and verified
2020-08-25 10:56:40,380 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-25 10:56:40,381 INFO    : Begin to train indi0001
Files already downloaded and verified
Files already downloaded and verified
2020-08-25 10:57:40,516 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-25 10:57:40,517 INFO    : Begin to train indi0002
Files already downloaded and verified
Files already downloaded and verified
2020-08-25 11:02:40,716 INFO    : GPU_QUERY-None of the GPU is occupied
2020-08-25 11:02:40,720 INFO    : Add record into cache, id:831bfb3f88a125297edbf9deb98e30ffc8be4b20c140e4c29d70497d, acc:0.00000
2020-08-25 11:02:40,724 INFO    : Add record into cache, id:7ec9dc0cce6d24d94890ed2069027ccd7ad61e536d8909b216d2c805, acc:0.00000
2020-08-25 11:02:40,729 INFO    : Add record into cache, id:e9c128d79771d9ae8b6a4822a2d6bdc00cf0fcae6d3d1bb8ff99bc60, acc:0.00000
2020-08-25 11:02:40,740 INFO    : EVOLVE[0-gen]-Finish the evaluation
2020-08-25 11:02:40,745 INFO    : EVOLVE[1-gen]-Begin to crossover and mutation
2020-08-25 11:02:40,748 WARNING : The 2-th try to find the position for do crossover
2020-08-25 11:02:40,753 WARNING : The 3-th try to find the position for do crossover
2020-08-25 11:02:40,753 WARNING : The 4-th try to find the position for do crossover
2020-08-25 11:02:40,753 INFO    : Position 1 for indi0002, positions 1 for indi0000
2020-08-25 11:02:40,754 INFO    : Change the input channel of unit at 1 to 64 that is the output channel of unit at 0 in indi0002
2020-08-25 11:02:40,754 INFO    : Change the input channel of unit at 1 to 64 that is the output channel of unit at 0 in indi0000
2020-08-25 11:02:40,754 INFO    : CROSSOVER-2 offspring are generated, new:2, others:0
2020-08-25 11:02:40,768 INFO    : MUTATION-mutated individuals:0[ADD: 0,REMOVE: 0,CHANNEL: 0,POOL: 0, no_changes:2
2020-08-25 11:02:40,777 INFO    : EVOLVE[1-gen]-Finish crossover and mutation
2020-08-25 11:02:40,778 INFO    : EVOLVE[1-gen]-Begin to evaluate the fitness
2020-08-25 11:02:40,779 INFO    : Begin to generate python files
2020-08-25 11:02:40,797 INFO    : Finish the generation of python files
2020-08-25 11:02:40,803 INFO    : Query fitness from cache
2020-08-25 11:02:40,809 INFO    : Hit the cache for indi0000, key:831bfb3f88a125297edbf9deb98e30ffc8be4b20c140e4c29d70497d, acc:0.00000, assigned_acc:-1.00000
2020-08-25 11:02:40,819 INFO    : Hit the cache for indi0001, key:e9c128d79771d9ae8b6a4822a2d6bdc00cf0fcae6d3d1bb8ff99bc60, acc:0.00000, assigned_acc:-1.00000
2020-08-25 11:02:40,819 INFO    : Total hit 2 individuals for fitness
2020-08-25 11:02:40,819 INFO    : indi0000 has inherited the fitness as 0.00000, no need to evaluate
2020-08-25 11:02:40,822 INFO    : indi0001 has inherited the fitness as 0.00000, no need to evaluate
2020-08-25 11:02:40,825 INFO    : None offspring has been evaluated
2020-08-25 11:02:40,828 INFO    : EVOLVE[1-gen]-Finish the evaluation
Traceback (most recent call last):
  File "evolve.py", line 114, in <module>
    evoCNN.do_work(max_gen=20)
  File "evolve.py", line 107, in do_work
    self.environment_selection()
  File "evolve.py", line 59, in environment_selection
    min_idx = np.argmin(first_selectd_v_list)
  File "<__array_function__ internals>", line 6, in argmin
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 1267, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

I've also 20gb of RAM left when i got this error. Also, the fitness values are 0 at all times. Is there any way to fix this?

**Comment by yn-sun** [comment]
I guess all the individuals having the accuracy of zeros. Please check why you got thus result first.

Sent from my iPhone

On Aug 25, 2020, at 19:07, n-b37 <notifications@github.com> wrote:

﻿

2020-08-25 10:54:39,366 INFO : *************************
2020-08-25 10:54:39,367 INFO : Initialize...
2020-08-25 10:54:39,375 INFO : EVOLVE[0-gen]-Begin to evaluate the fitness
2020-08-25 10:54:39,375 INFO : Begin to generate python files
2020-08-25 10:54:39,411 INFO : Finish the generation of python files
2020-08-25 10:54:39,412 INFO : Query fitness from cache
2020-08-25 10:54:39,413 INFO : Total hit 0 individuals for fitness
2020-08-25 10:55:39,475 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-25 10:55:39,476 INFO : Begin to train indi0000
Files already downloaded and verified
Files already downloaded and verified
2020-08-25 10:56:40,380 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-25 10:56:40,381 INFO : Begin to train indi0001
Files already downloaded and verified
Files already downloaded and verified
2020-08-25 10:57:40,516 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-25 10:57:40,517 INFO : Begin to train indi0002
Files already downloaded and verified
Files already downloaded and verified
2020-08-25 11:02:40,716 INFO : GPU_QUERY-None of the GPU is occupied
2020-08-25 11:02:40,720 INFO : Add record into cache, id:831bfb3f88a125297edbf9deb98e30ffc8be4b20c140e4c29d70497d, acc:0.00000
2020-08-25 11:02:40,724 INFO : Add record into cache, id:7ec9dc0cce6d24d94890ed2069027ccd7ad61e536d8909b216d2c805, acc:0.00000
2020-08-25 11:02:40,729 INFO : Add record into cache, id:e9c128d79771d9ae8b6a4822a2d6bdc00cf0fcae6d3d1bb8ff99bc60, acc:0.00000
2020-08-25 11:02:40,740 INFO : EVOLVE[0-gen]-Finish the evaluation
2020-08-25 11:02:40,745 INFO : EVOLVE[1-gen]-Begin to crossover and mutation
2020-08-25 11:02:40,748 WARNING : The 2-th try to find the position for do crossover
2020-08-25 11:02:40,753 WARNING : The 3-th try to find the position for do crossover
2020-08-25 11:02:40,753 WARNING : The 4-th try to find the position for do crossover
2020-08-25 11:02:40,753 INFO : Position 1 for indi0002, positions 1 for indi0000
2020-08-25 11:02:40,754 INFO : Change the input channel of unit at 1 to 64 that is the output channel of unit at 0 in indi0002
2020-08-25 11:02:40,754 INFO : Change the input channel of unit at 1 to 64 that is the output channel of unit at 0 in indi0000
2020-08-25 11:02:40,754 INFO : CROSSOVER-2 offspring are generated, new:2, others:0
2020-08-25 11:02:40,768 INFO : MUTATION-mutated individuals:0[ADD: 0,REMOVE: 0,CHANNEL: 0,POOL: 0, no_changes:2
2020-08-25 11:02:40,777 INFO : EVOLVE[1-gen]-Finish crossover and mutation
2020-08-25 11:02:40,778 INFO : EVOLVE[1-gen]-Begin to evaluate the fitness
2020-08-25 11:02:40,779 INFO : Begin to generate python files
2020-08-25 11:02:40,797 INFO : Finish the generation of python files
2020-08-25 11:02:40,803 INFO : Query fitness from cache
2020-08-25 11:02:40,809 INFO : Hit the cache for indi0000, key:831bfb3f88a125297edbf9deb98e30ffc8be4b20c140e4c29d70497d, acc:0.00000, assigned_acc:-1.00000
2020-08-25 11:02:40,819 INFO : Hit the cache for indi0001, key:e9c128d79771d9ae8b6a4822a2d6bdc00cf0fcae6d3d1bb8ff99bc60, acc:0.00000, assigned_acc:-1.00000
2020-08-25 11:02:40,819 INFO : Total hit 2 individuals for fitness
2020-08-25 11:02:40,819 INFO : indi0000 has inherited the fitness as 0.00000, no need to evaluate
2020-08-25 11:02:40,822 INFO : indi0001 has inherited the fitness as 0.00000, no need to evaluate
2020-08-25 11:02:40,825 INFO : None offspring has been evaluated
2020-08-25 11:02:40,828 INFO : EVOLVE[1-gen]-Finish the evaluation
Traceback (most recent call last):
File "evolve.py", line 114, in
evoCNN.do_work(max_gen=20)
File "evolve.py", line 107, in do_work
self.environment_selection()
File "evolve.py", line 59, in environment_selection
min_idx = np.argmin(first_selectd_v_list)
File "<array_function internals>", line 6, in argmin
File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 1267, in argmin
return _wrapfunc(a, 'argmin', axis=axis, out=out)
File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
return _wrapit(obj, method, *args, **kwds)
File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 47, in _wrapit
result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

I've also 20gb of RAM left when i got this error. Also, the fitness values are 0 at all times. Is there any way to fix this?

**Comment by xiewenqing** [comment]
Hi,You can try to modify loss.data[0] to loss.item() in lines 101 and 117 in cifar10.py

**Comment by yn-sun** [comment]
> Hi,You can try to modify loss.data[0] to loss.item() in lines 101 and 117 in cifar10.py

Yeah, this is an issue caused by the Pytorch vesion.
