### ISSUE TITLE
log file not getting created. Not able to understand why this error is occuring.

### ISSUE THREAD

**Issue by n-b37** [yn-sun/cnn-ga#6]
2020-08-06 20:24:52,755 INFO    : *************************
2020-08-06 20:24:52,755 INFO    : Initialize...
2020-08-06 20:24:52,765 INFO    : EVOLVE[0-gen]-Begin to evaluate the fitness
2020-08-06 20:24:52,765 INFO    : Begin to generate python files
2020-08-06 20:24:52,815 INFO    : Finish the generation of python files
2020-08-06 20:24:52,815 INFO    : Query fitness from cache
2020-08-06 20:24:52,815 INFO    : Total hit 0 individuals for fitness
2020-08-06 20:25:52,926 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-06 20:25:52,926 INFO    : Begin to train indi0000
Files already downloaded and verified
Files already downloaded and verified
Exception occurs, file:indi0000, pid:1424...[Errno 2] No such file or directory: './log/indi0000.txt'
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\cnn-ga\cnn-ga\scripts\indi0000.py", line 164, in do_work
    m.log_record('Used GPU#%s, worker name:%s[%d]'%(gpu_id, multiprocessing.current_process().name, os.getpid()), first_time=True)
  File "C:\Users\cnn-ga\cnn-ga\scripts\indi0000.py", line 101, in log_record
    f = open('./log/%s.txt'%(self.file_id), file_mode)
FileNotFoundError: [Errno 2] No such file or directory: './log/indi0000.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cnn-ga\cnn-ga\scripts\indi0000.py", line 170, in do_work
    m.log_record('Exception occur:%s'%(str(e)))
  File "C:\Users\cnn-ga\cnn-ga\scripts\indi0000.py", line 101, in log_record
    f = open('./log/%s.txt'%(self.file_id), file_mode)
FileNotFoundError: [Errno 2] No such file or directory: './log/indi0000.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anaconda\anacondaa\envs\testt\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Anaconda\anacondaa\envs\testt\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\cnn-ga\cnn-ga\scripts\indi0000.py", line 172, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
  File "C:\Users\cnn-ga\cnn-ga\scripts\indi0000.py", line 101, in log_record
    f = open('./log/%s.txt'%(self.file_id), file_mode)
FileNotFoundError: [Errno 2] No such file or directory: './log/indi0000.txt'

**Comment by yn-sun** [comment]
Please create the log directory manually before you running the codes

**Comment by n-b37** [comment]
Thank you so much!

**Comment by QAQureshi** [comment]
Hi, will you please tell me the version number of PyTorch you used to execute this code?
