### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './populations/after_00.txt'

### ISSUE THREAD

**Issue by TyjChristy** [yn-sun/cnn-ga#7]
2020-08-09 23:58:27,971 INFO    : *************************
2020-08-09 23:58:27,971 INFO    : Initialize from existing population data
2020-08-09 23:58:27,971 INFO    : Initialize from 0-th generation
Traceback (most recent call last):
  File "evolve.py", line 114, in <module>
    evoCNN.do_work(max_gen=20)
  File "evolve.py", line 84, in do_work
    pops = Utils.load_population('begin', gen_no)
  File "/home/guohy/cnnga/utils.py", line 365, in load_population
    f = open(after_file_path)
FileNotFoundError: [Errno 2] No such file or directory: './populations/after_00.txt'

Could you tell me how to solve the problem above?Thank you very much.

**Comment by n-b37** [comment]
Since the after_00.txt is not created yet, go to global.ini and change the value of is_running to 0.

**Comment by yn-sun** [comment]
> populations

please manually create the directory of "populations" before you running the code.

**Comment by TyjChristy** [comment]
> Since the after_00.txt is not created yet, go to global.ini and change the value of is_running to 0.

Thank you very much.

**Comment by TyjChristy** [comment]
> > populations
> 
> please manually create the directory of "populations" before you running the code.

Thank you very much.
