### ISSUE TITLE
local variable 'm' referenced before assignment

### ISSUE THREAD

**Issue by TyjChristy** [yn-sun/cnn-ga#8]
Traceback (most recent call last):
  File "/home/guohy/.conda/envs/guohy/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/guohy/.conda/envs/guohy/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/guohy/cnnga/scripts/indi0019.py", line 178, in do_work
    m.log_record('Finished-Acc:%.3f'%best_acc)
UnboundLocalError: local variable 'm' referenced before assignment

Could you tell me how to solve the problem?Thank you very much.

**Comment by yn-sun** [comment]
You could run "indi0019.py" seperately on the corresponding CUDA to see more details. Because m is an instance of the model, I guess the model did not create successfully. You could also send me this script for the checking.

**Comment by TyjChristy** [comment]
> You could run "indi0019.py" seperately on the corresponding CUDA to see more details. Because m is an instance of the model, I guess the model did not create successfully. You could also send me this script for the checking.

Thank you very much for your quick response.When I run "indi0019.py" , a new problem appears below:

Traceback (most recent call last):
  File "indi0019.py", line 14, in <module>
    from util import StatusUpdateTool
  File "../util.py", line 6, in <module>
    from genetic.population import Population, Individual, ResUnit, PoolUnit
ModuleNotFoundError: No module named 'genetic.population'

The "_init_.py"  already exists，could you tell me how to solve the problem ?
Thank you very much!

**Comment by yn-sun** [comment]
This is a problem about the library reference in Python. I suggest you learn some basic knowledge about python and then come back to the problem.
