### ISSUE TITLE
GPU_QUERY-No available GPU

### ISSUE THREAD

**Issue by iyashdesh** [yn-sun/cnn-ga#9]
hello, i am new to using a gpu, so sorry for the stupid question:
I get this error:

2020-08-14 19:13:26,978 INFO    : Total hit 0 individuals for fitness
2020-08-14 19:14:27,022 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:14:27,022 INFO    : Begin to train indi0000

0.0%
0.6%
2.6%
4.7%
6.8%
8.8%
10.9%
11.3%
11.4%
13.0%
15.1%
17.2%
19.2%
21.2%
23.3%
25.1%
27.2%
28.8%
31.0%
33.0%
35.2%
37.3%
39.4%
41.5%
43.3%
45.2%
47.2%
49.1%
51.1%
53.1%
55.1%
57.2%
59.2%
61.1%
63.0%
65.0%
66.9%
68.8%
70.5%
72.4%
74.4%
76.1%
78.1%
80.0%
82.0%
83.9%
85.8%
87.8%
89.8%
91.8%
93.8%
95.9%
97.2%
98.6%
100.0%2020-08-14 19:15:27,398 INFO    : GPU_QUERY-No available GPU
2020-08-14 19:20:27,442 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:20:27,443 INFO    : Begin to train indi0001
2020-08-14 19:21:27,494 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:21:27,495 INFO    : Begin to train indi0002
2020-08-14 19:22:27,554 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:22:27,555 INFO    : Begin to train indi0003
2020-08-14 19:23:27,608 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:23:27,608 INFO    : Begin to train indi0004
2020-08-14 19:24:27,659 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:24:27,659 INFO    : Begin to train indi0005
2020-08-14 19:25:27,711 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:25:27,712 INFO    : Begin to train indi0006
2020-08-14 19:26:27,762 INFO    : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use

global.ini:

[settings]
pop_size = 20
gpu_num = 
genetic_prob = 0.9, 0.2
mutation_probs = 0.7, 0.1, 0.1, 0.1

[evolution_status]
is_running = 1

[gpu_running_status]
cpu0 = 
cpu1 = 
cpu2 = 
cpu3 = 
cpu4 = 
cpu5 = 

[network]
max_length = 50
conv_limit = 5, 15
pool_limit = 3, 3
input_channel = 3
num_class = 10
epoch = 350
output_channel = 64, 128, 256

- I have one gpu NVIDIA GeForce RTX 2080 SUPER
- i have tried setting gpu_num=1 and still get errors
- not sure how to fix this issue, please advice. 

thank you

**Comment by yn-sun** [comment]
it looks correct

Sent from my iPhone

On Aug 15, 2020, at 02:32, Yash.D <notifications@github.com> wrote:

﻿

hello, i am new to using a gpu, so sorry for the stupid question:
I get this error:

2020-08-14 19:13:26,978 INFO : Total hit 0 individuals for fitness
2020-08-14 19:14:27,022 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:14:27,022 INFO : Begin to train indi0000

0.0%
0.6%
2.6%
4.7%
6.8%
8.8%
10.9%
11.3%
11.4%
13.0%
15.1%
17.2%
19.2%
21.2%
23.3%
25.1%
27.2%
28.8%
31.0%
33.0%
35.2%
37.3%
39.4%
41.5%
43.3%
45.2%
47.2%
49.1%
51.1%
53.1%
55.1%
57.2%
59.2%
61.1%
63.0%
65.0%
66.9%
68.8%
70.5%
72.4%
74.4%
76.1%
78.1%
80.0%
82.0%
83.9%
85.8%
87.8%
89.8%
91.8%
93.8%
95.9%
97.2%
98.6%
100.0%2020-08-14 19:15:27,398 INFO : GPU_QUERY-No available GPU
2020-08-14 19:20:27,442 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:20:27,443 INFO : Begin to train indi0001
2020-08-14 19:21:27,494 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:21:27,495 INFO : Begin to train indi0002
2020-08-14 19:22:27,554 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:22:27,555 INFO : Begin to train indi0003
2020-08-14 19:23:27,608 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:23:27,608 INFO : Begin to train indi0004
2020-08-14 19:24:27,659 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:24:27,659 INFO : Begin to train indi0005
2020-08-14 19:25:27,711 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use
2020-08-14 19:25:27,712 INFO : Begin to train indi0006
2020-08-14 19:26:27,762 INFO : GPU_QUERY-Available GPUs are: [0], choose GPU#0 to use

global.ini:

[settings]
pop_size = 20
gpu_num =
genetic_prob = 0.9, 0.2
mutation_probs = 0.7, 0.1, 0.1, 0.1

[evolution_status]
is_running = 1

[gpu_running_status]
cpu0 =
cpu1 =
cpu2 =
cpu3 =
cpu4 =
cpu5 =

[network]
max_length = 50
conv_limit = 5, 15
pool_limit = 3, 3
input_channel = 3
num_class = 10
epoch = 350
output_channel = 64, 128, 256

  *   I have one gpu NVIDIA GeForce RTX 2080 SUPER
  *   i have tried setting gpu_num=1 and still get errors
  *   not sure how to fix this issue, please advice.

thank you

**Comment by iyashdesh** [comment]
it runs until this point:

2020-08-15 10:44:23,368 INFO    : Add record into cache, id:de54f5f8e8503dfc795dc061368d3f5bbca7d3dd267d5e592409c9fa, acc:0.00000
2020-08-15 10:44:23,372 INFO    : Add record into cache, id:61c0285cb23510454b3a08b37f64de8211466825ff18422a6de73e41, acc:0.00000
2020-08-15 10:44:23,376 INFO    : Add record into cache, id:12f80de5959bd27c8b264821b447a88b1f3d03bb73f2705907ae69a4, acc:0.00000
2020-08-15 10:44:23,379 INFO    : Add record into cache, id:5276aa606007c89d9dca4520959843072b7887d02b3822e25feb7678, acc:0.00000
2020-08-15 10:44:23,382 INFO    : Add record into cache, id:750599cbc207212d90905d42c1efa210e67cde6417c8590446ba0b67, acc:0.00000
2020-08-15 10:44:23,386 INFO    : Add record into cache, id:5e3f1c0d89a852df18e3b1f94b553add094bc4d8ddc644ded8fdb7e9, acc:0.00000
2020-08-15 10:44:23,389 INFO    : Add record into cache, id:6ed92592051f430ba3e8b6ca037a86a26710f3ac7ebdc3bc1b10f988, acc:0.00000
2020-08-15 10:44:23,392 INFO    : EVOLVE[1-gen]-Finish the evaluation

...

ValueError: attempt to get argmin of an empty sequence

do you know if there's a way to get around this error?

thank you for helping

**Comment by yn-sun** [comment]
The accuracy of zeros commonly resulted by the out-of-memory error. That is because the model is too large to run on the GPU. You could check the corresponding log file of the individual.

As for the error, I cannot help too much because there is no information that I could help to locate, such as which file and which line.

**Comment by iyashdesh** [comment]
apologies. Here is more error information:

2020-08-16 12:33:13,459 INFO    : EVOLVE[1-gen]-Finish the evaluation
Traceback (most recent call last):

  File "C:\Users\yash\Desktop\project\cnn-ga-master\evolve.py", line 114, in <module>
    evoCNN.do_work(max_gen=20)

  File "C:\Users\yash\Desktop\project\cnn-ga-master\evolve.py", line 107, in do_work
    self.environment_selection()

  File "C:\Users\yash\Desktop\project\cnn-ga-master\evolve.py", line 59, in environment_selection
    min_idx = np.argmin(first_selectd_v_list)

  File "<__array_function__ internals>", line 6, in argmin

  File "C:\Users\yash\Anaconda3\envs\tf-gpu\lib\site-packages\numpy\core\fromnumeric.py", line 1267, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)

  File "C:\Users\yash\Anaconda3\envs\tf-gpu\lib\site-packages\numpy\core\fromnumeric.py", line 58, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)

  File "C:\Users\yash\Anaconda3\envs\tf-gpu\lib\site-packages\numpy\core\fromnumeric.py", line 47, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)

ValueError: attempt to get argmin of an empty sequence

Thank you for helping

**Comment by iyashdesh** [comment]
this is what is in the log file:
[2020-08-16 12:26:16.371305]-Used GPU#0, worker name:Process-38[6312]
[2020-08-16 12:26:20.212117]-Exception occur:invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
[2020-08-16 12:26:20.216121]-Finished-Acc:0.000

**Comment by yn-sun** [comment]
This need you to further debug to locate the source.
